# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: 5
  reconnect: true

development:
  <<: *default
  database: blacklights
  pool: 5
  username: blacklights
  password: B8b4HHSBhYsUBQqb
  host: 127.0.0.1
  port: 3306


test:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: blacklights_test
  username: blacklights
  password: B8b4HHSBhYsUBQqb

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
